### ISSUE TITLE
No Password Verification

### ISSUE THREAD

**Issue by shazaman23** [jfarnworth/GroceryStoreApp#2]
The user creation does not notify about password changes (it's unclear if the password is really changed. There should at least be a pop up window that says "you changed the password to _________" etc). Also, the password is not verified. So I can just use "password" and it verifies. Not very secure. There should be some strength tests or something.

**Comment by jfarnworth** [comment]
I'm gonna say this isn't a bug. Since Mr. Smith is in charge of creating users and the admin is in charge of setting passwords, password strength is his concern. If he wants his employees to not even have a password then they can do that. If he wants his employees to have their social security numbers as their passwords they can do that.
